version: "2.2"
services:
  tronics:
    container_name: gocoin
    build: .
    expose:
      - "8082"
    env_file:
      - ./config/dev.env
    depends_on:
      - mongo
    ports:
      - "8082:8082"
  mongo:
    image: mongo
    container_name: "gocoin"
    ports:
      - "27017:27017"