// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/orderbook.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EnumSide int32

const (
	EnumSide_BUY  EnumSide = 0
	EnumSide_SELL EnumSide = 1
)

var EnumSide_name = map[int32]string{
	0: "BUY",
	1: "SELL",
}

var EnumSide_value = map[string]int32{
	"BUY":  0,
	"SELL": 1,
}

func (x EnumSide) String() string {
	return proto.EnumName(EnumSide_name, int32(x))
}

func (EnumSide) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e6b2982dec9a4117, []int{0}
}

type OrderInfoRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderInfoRequest) Reset()         { *m = OrderInfoRequest{} }
func (m *OrderInfoRequest) String() string { return proto.CompactTextString(m) }
func (*OrderInfoRequest) ProtoMessage()    {}
func (*OrderInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b2982dec9a4117, []int{0}
}

func (m *OrderInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderInfoRequest.Unmarshal(m, b)
}
func (m *OrderInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderInfoRequest.Marshal(b, m, deterministic)
}
func (m *OrderInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderInfoRequest.Merge(m, src)
}
func (m *OrderInfoRequest) XXX_Size() int {
	return xxx_messageInfo_OrderInfoRequest.Size(m)
}
func (m *OrderInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderInfoRequest proto.InternalMessageInfo

func (m *OrderInfoRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type OrderInfoReply struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderInfoReply) Reset()         { *m = OrderInfoReply{} }
func (m *OrderInfoReply) String() string { return proto.CompactTextString(m) }
func (*OrderInfoReply) ProtoMessage()    {}
func (*OrderInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b2982dec9a4117, []int{1}
}

func (m *OrderInfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderInfoReply.Unmarshal(m, b)
}
func (m *OrderInfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderInfoReply.Marshal(b, m, deterministic)
}
func (m *OrderInfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderInfoReply.Merge(m, src)
}
func (m *OrderInfoReply) XXX_Size() int {
	return xxx_messageInfo_OrderInfoReply.Size(m)
}
func (m *OrderInfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderInfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_OrderInfoReply proto.InternalMessageInfo

func (m *OrderInfoReply) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type Order struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Price                float64  `protobuf:"fixed64,2,opt,name=Price,proto3" json:"Price,omitempty"`
	Quantity             float64  `protobuf:"fixed64,3,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	Side                 EnumSide `protobuf:"varint,4,opt,name=Side,proto3,enum=orderbook.EnumSide" json:"Side,omitempty"`
	Timestamp            uint32   `protobuf:"varint,5,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	OwnerUsername        string   `protobuf:"bytes,6,opt,name=OwnerUsername,proto3" json:"OwnerUsername,omitempty"`
	CreatedAt            string   `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b2982dec9a4117, []int{2}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Order) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Order) GetQuantity() float64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Order) GetSide() EnumSide {
	if m != nil {
		return m.Side
	}
	return EnumSide_BUY
}

func (m *Order) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Order) GetOwnerUsername() string {
	if m != nil {
		return m.OwnerUsername
	}
	return ""
}

func (m *Order) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Order) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type GreetingServiceRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetingServiceRequest) Reset()         { *m = GreetingServiceRequest{} }
func (m *GreetingServiceRequest) String() string { return proto.CompactTextString(m) }
func (*GreetingServiceRequest) ProtoMessage()    {}
func (*GreetingServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b2982dec9a4117, []int{3}
}

func (m *GreetingServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetingServiceRequest.Unmarshal(m, b)
}
func (m *GreetingServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetingServiceRequest.Marshal(b, m, deterministic)
}
func (m *GreetingServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetingServiceRequest.Merge(m, src)
}
func (m *GreetingServiceRequest) XXX_Size() int {
	return xxx_messageInfo_GreetingServiceRequest.Size(m)
}
func (m *GreetingServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetingServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetingServiceRequest proto.InternalMessageInfo

func (m *GreetingServiceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GreetingServiceReply struct {
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetingServiceReply) Reset()         { *m = GreetingServiceReply{} }
func (m *GreetingServiceReply) String() string { return proto.CompactTextString(m) }
func (*GreetingServiceReply) ProtoMessage()    {}
func (*GreetingServiceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b2982dec9a4117, []int{4}
}

func (m *GreetingServiceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetingServiceReply.Unmarshal(m, b)
}
func (m *GreetingServiceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetingServiceReply.Marshal(b, m, deterministic)
}
func (m *GreetingServiceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetingServiceReply.Merge(m, src)
}
func (m *GreetingServiceReply) XXX_Size() int {
	return xxx_messageInfo_GreetingServiceReply.Size(m)
}
func (m *GreetingServiceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetingServiceReply.DiscardUnknown(m)
}

var xxx_messageInfo_GreetingServiceReply proto.InternalMessageInfo

func (m *GreetingServiceReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("orderbook.EnumSide", EnumSide_name, EnumSide_value)
	proto.RegisterType((*OrderInfoRequest)(nil), "orderbook.OrderInfoRequest")
	proto.RegisterType((*OrderInfoReply)(nil), "orderbook.OrderInfoReply")
	proto.RegisterType((*Order)(nil), "orderbook.Order")
	proto.RegisterType((*GreetingServiceRequest)(nil), "orderbook.GreetingServiceRequest")
	proto.RegisterType((*GreetingServiceReply)(nil), "orderbook.GreetingServiceReply")
}

func init() {
	proto.RegisterFile("proto/orderbook.proto", fileDescriptor_e6b2982dec9a4117)
}

var fileDescriptor_e6b2982dec9a4117 = []byte{
	// 395 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0xbb, 0x89, 0xdd, 0xd8, 0x03, 0x0d, 0xd6, 0x50, 0xd0, 0x12, 0xa8, 0x30, 0x16, 0x02,
	0x0b, 0xa1, 0x16, 0x99, 0x0b, 0xd7, 0x56, 0xaa, 0x0a, 0x52, 0xa5, 0x96, 0x0d, 0x3d, 0x80, 0x90,
	0x90, 0x63, 0x0f, 0xd1, 0x8a, 0xf8, 0x0f, 0xeb, 0x35, 0x28, 0xdf, 0x9b, 0x0f, 0x80, 0xbc, 0x8e,
	0x13, 0x13, 0xa2, 0xde, 0xfc, 0x7e, 0xef, 0xed, 0x8c, 0x77, 0x76, 0xe0, 0x41, 0xa9, 0x0a, 0x5d,
	0x9c, 0x14, 0x2a, 0x25, 0x35, 0x2b, 0x8a, 0x1f, 0xc7, 0x46, 0xa3, 0xbb, 0x06, 0x41, 0x00, 0xde,
	0x55, 0x23, 0x3e, 0xe4, 0xdf, 0x0b, 0x41, 0x3f, 0x6b, 0xaa, 0x34, 0x8e, 0x61, 0x20, 0x53, 0xce,
	0x7c, 0x16, 0x5a, 0x62, 0x20, 0xd3, 0xe0, 0x1d, 0x8c, 0x7b, 0x99, 0x72, 0xb1, 0xc4, 0x17, 0x60,
	0x9b, 0x12, 0x26, 0x74, 0x27, 0xf2, 0x8e, 0x37, 0x1d, 0x4c, 0x52, 0xb4, 0x76, 0xf0, 0x87, 0x81,
	0x6d, 0xc0, 0x76, 0x4d, 0x3c, 0x04, 0xfb, 0x5a, 0xc9, 0x84, 0xf8, 0xc0, 0x67, 0x21, 0x13, 0xad,
	0xc0, 0x09, 0x38, 0x1f, 0xeb, 0x38, 0xd7, 0x52, 0x2f, 0xf9, 0xd0, 0x18, 0x6b, 0x8d, 0x2f, 0xc1,
	0x9a, 0xca, 0x94, 0xb8, 0xe5, 0xb3, 0x70, 0x1c, 0xdd, 0xef, 0xb5, 0x3c, 0xcf, 0xeb, 0xac, 0xb1,
	0x84, 0x09, 0xe0, 0x13, 0x70, 0x3f, 0xc9, 0x8c, 0x2a, 0x1d, 0x67, 0x25, 0xb7, 0x7d, 0x16, 0x1e,
	0x88, 0x0d, 0xc0, 0xe7, 0x70, 0x70, 0xf5, 0x3b, 0x27, 0x75, 0x53, 0x91, 0xca, 0xe3, 0x8c, 0xf8,
	0xbe, 0xcf, 0x42, 0x57, 0xfc, 0x0b, 0xf1, 0x08, 0x20, 0x51, 0x14, 0x6b, 0x4a, 0xbf, 0xc5, 0x9a,
	0x8f, 0x4c, 0xc4, 0x5d, 0x91, 0x53, 0xdd, 0xd8, 0x75, 0x99, 0x76, 0xb6, 0xd3, 0xda, 0x2b, 0x72,
	0xaa, 0x83, 0xd7, 0xf0, 0xf0, 0x42, 0x11, 0x69, 0x99, 0xcf, 0xa7, 0xa4, 0x7e, 0xc9, 0x84, 0xba,
	0xd1, 0x22, 0x58, 0xa6, 0x29, 0x33, 0x47, 0xcc, 0x77, 0xf0, 0x06, 0x0e, 0xff, 0x4b, 0x37, 0x43,
	0xe6, 0x30, 0xca, 0xa8, 0xaa, 0xe2, 0x79, 0x3b, 0x24, 0x57, 0x74, 0xf2, 0xd5, 0x11, 0x38, 0xdd,
	0x9d, 0x71, 0x04, 0xc3, 0xb3, 0x9b, 0xcf, 0xde, 0x1e, 0x3a, 0x60, 0x4d, 0xcf, 0x2f, 0x2f, 0x3d,
	0x16, 0x7d, 0xed, 0xbd, 0xe9, 0xaa, 0x22, 0xbe, 0x87, 0xbb, 0x17, 0xa4, 0xd7, 0x18, 0x1f, 0x6f,
	0x3f, 0x59, 0x6f, 0x01, 0x26, 0x8f, 0x76, 0x9b, 0xe5, 0x62, 0x19, 0xec, 0x45, 0x09, 0xdc, 0xdb,
	0xfa, 0x5d, 0xbc, 0x06, 0xa7, 0x43, 0xf8, 0xac, 0x77, 0x76, 0xf7, 0x10, 0x26, 0x4f, 0x6f, 0x8b,
	0x98, 0x26, 0x67, 0xf6, 0x97, 0xe1, 0x49, 0x39, 0x9b, 0xed, 0x9b, 0x7d, 0x7d, 0xfb, 0x37, 0x00,
	0x00, 0xff, 0xff, 0x1d, 0x01, 0x32, 0xc9, 0xc8, 0x02, 0x00, 0x00,
}
